### PR TITLE
JMA catalog import unit tests

### PR DESCRIPTION
**Pull request by thbeutin**
JMA fake test data derived from real catalog.
The real catalog cannot be provided here for IP reasons.

### CODE REVIEW

**Comment by wsavran** [comment]
hi thomas, here are important methods to have tested.

all the getters
get_magnitudes()
get_latitudes()
get_longitudes()
get_datetimes()
get_epochtimes()
update_catalog_stats()

eventually we need to test to_json() and from_json() as well.

**Comment by thbeutin** [comment]
I test now

- `get_magnitudes()`
- `get_latitudes()`
- `get_longitudes()`
- `get_datetimes()`
- `get_epoch_times()`
- `update_catalog_stats()`

(although some of them are called inside `update_catalog_stats()` anyway, which itself is called inside `load_catalog()`). Some basic asserts are implemented. I spared out `to_json()` and `from_json()` because there is nothing in the tests yet. And the AbstractBaseCatalog has for now just the `from_json()` method, and this is already implemented there.

**Comment by wsavran** [comment]
- in numpy.testing there are functions called [assert_allclose()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_allclose.html#numpy.testing.assert_allclose) to verify numpy arrays.

- we should verify that epoch times are properly parsed. this can be done by having an event that would correspond to an epoch time of 0.

you are fine to ignore the to_dict() and from_dict() and from_json() for the time being.

**Comment by wsavran** [comment]
i cant view the notebook bc it doesn't render in github, but the last line looks like the error. in general you should use those numpy testing routines for comparing floating point numbers. 

can you explain what the weird floating point error?

**Comment by thbeutin** [comment]
@wsavran Bill, is the floating point issue demonstrated in `tests/artifacts/Testing/JMA-catalog/dateStringParsing.ipynb` new to you? I wasn't aware of it, but the unit test brought it up.
I'll work on it to fix this.

**Comment by thbeutin** [comment]
> i cant view the notebook bc it doesn't render in github, but the last line looks like the error. in general you should use those numpy testing routines for comparing floating point numbers.

here i want to make sure a epoch seconds -> datetime object -> epoch seconds works by matching the exact number of `ms`.


> can you explain what the weird floating point error?

[dateStringParsing.pdf](https://github.com/SCECcode/csep2/files/4451323/dateStringParsing.pdf)
(i cannot create a full page screenshot)

**Comment by wsavran** [comment]
those floating point numbers look the same to me, just rounding error and python print bugs. how do they compare when you use a proper floating point comparison eg numpy.testing.allclose()?

**Comment by thbeutin** [comment]
> those floating point numbers look the same to me, just rounding error and python print bugs. how do they compare when you use a proper floating point comparison eg numpy.testing.allclose()?

I do, but w/ zero tolerance:
```
numpy.testing.assert_allclose(_datetimes, _JmaCsvCatalogObject.catalog['timestamp'],
                                  err_msg='timestamp mismatch',
                                  verbose=True, rtol=0, atol=0)
```

**Comment by wsavran** [comment]
any reason for that? i think that is only ok for integer comparisons. here is how they use atol and rtol: `atol + rtol * abs(desired).`

**Comment by wsavran** [comment]
nice, it looks fixed and the last test is failing because of a typo

**Comment by thbeutin** [comment]
> any reason for that? i think that is only ok for integer comparisons. here is how they use atol and rtol: `atol + rtol * abs(desired).`

this are int values (epoch seconds in `ms`) ;)

**Comment by thbeutin** [comment]
> nice, it looks fixed and the last test is failing because of a typo. once the build passes i can merge

is there any chance to figure out (here in this web app) which test fails? There is one failure, but it's _in someone else's department_(tm):
```
tb@gurke:~/devel/csep2$ time nice -n 19 pytest-3 
============================================================= test session starts ==============================================================
platform linux -- Python 3.6.9, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/tb/devel/csep2, inifile:
collected 96 items                                                                                                                             

tests/test_JmaCsvCatalog.py .                                                                                                            [  1%]
tests/test_UCERF3Forecast.py ....                                                                                                        [  5%]
tests/test_acceptance_ucerf3_experiment.py .                                                                                             [  6%]
tests/test_adaptiveHistogram.py ......                                                                                                   [ 12%]
tests/test_basic_types_utils.py .                                                                                                        [ 13%]
tests/test_calc.py ......                                                                                                                [ 19%]
tests/test_comcat.py ......                                                                                                              [ 26%]
tests/test_create_catalog.py ..                                                                                                          [ 28%]
tests/test_csep1_evaluations.py ....                                                                                                     [ 32%]
tests/test_evaluations.py ....F.                                                                                                         [ 38%]
tests/test_file_system.py ..                                                                                                             [ 40%]
tests/test_math.py ...............                                                                                                       [ 56%]
tests/test_spatial.py ..............                                                                                                     [ 70%]
tests/test_stats.py ................                                                                                                     [ 87%]
tests/test_system.py ....                                                                                                                [ 91%]
tests/test_time_utilities.py ......                                                                                                      [ 97%]
tests/test_workflow.py ..                                                                                                                [100%]

=================================================================== FAILURES ===================================================================
____________________________________________________ TestPoissonLikelihood.test_likelihood _____________________________________________________

self = <tests.test_evaluations.TestPoissonLikelihood testMethod=test_likelihood>

    def test_likelihood(self):
        qs, obs_ll, simulated_ll = poisson_likelihood_test(self.forecast_data, self.observed_data, num_simulations=1,
                                                           random_numbers=self.random_matrix, use_observed_counts=True)
    
        # very basic result to pass "laugh" test
        self.assertEqual(qs, 1)
    
        # forecast and observation are the same, sum(np.log(poisson(1, 1))) = -4
        self.assertEqual(obs_ll, -4)
    
        # calculated by hand given the expected catalog, see explanation in zechar et al., 2010.
>       self.assertEqual(simulated_ll[0], -7.178053830347945)
E       AssertionError: (-7.1780538303479444+0j) != -7.178053830347945

tests/test_evaluations.py:152: AssertionError
==================================================== 1 failed, 95 passed in 168.30 seconds =====================================================

real	4m11.951s
user	3m47.120s
sys	0m4.756s
tb@gurke:~/devel/csep2$
``` 
I'll report this as an issue now - can take up to an hour on my system :-/

**Comment by thbeutin** [comment]
> > nice, it looks fixed and the last test is failing because of a typo. once the build passes i can merge
> 
> is there any chance to figure out (here in this web app) which test fails? There is one failure, but it's _in someone else's department_(tm):
> [...]
> I'll report this as an issue now - can take up to an hour on my system :-/

I created #22 to address this.

**Comment by wsavran** [comment]
i think you might need to merge dev into your branch. it looks like there are some inconsistencies, because your test results are different from those run on the ci.

**Comment by thbeutin** [comment]
> i think you might need to merge dev into your branch. 

i'll try to do this. `git pull origin` or `git pull origin dev` or `git merge origin` or `git merge origin dev` all show `Already up to date.`

> it looks like there are some inconsistencies, because your test results are different from those run on the ci.

Is there any CI output visible to _"The User"_? It just shows there is an error, but that's it :(

**Comment by wsavran** [comment]
i'm not sure if you can see anything, but if you can it'll show up in the comments here. anyway, here is a link to the failing build. let me know if this works: https://travis-ci.com/github/SCECcode/csep2/builds/159396979.

anyway, git pull origin dev will probably show up-to-date because that is pointing to your fork of the repository. you'll need to merge upstream/dev into your origin/dev branch. 

the ci test suite is running off the upstream branches, so its possible they are different.

**Comment by thbeutin** [comment]
> i'm not sure if you can see anything, but if you can it'll show up in the comments here. anyway, here is a link to the failing build. let me know if this works: https://travis-ci.com/github/SCECcode/csep2/builds/159396979.

Not really: `There was an error while trying to fetch the log.` :(



> anyway, git pull origin dev will probably show up-to-date because that is pointing to your fork of the repository. you'll need to merge upstream/dev into your origin/dev branch.

Yeah, in the first place i got confused by `origin` and `upstream`. After getting this clear in my mind i found the `--all` option for `git pull -v --all`. Than, a `git merge -v upstream/dev` wasn't too far away.


> the ci test suite is running off the upstream branches, so its possible they are different.

So, it takes `upstream/dev`, applies my pull request, and runs the unit tests?

**Comment by wsavran** [comment]
yeah thats basically what its doing. everything looks good. im going to merge this into dev.

**Comment by thbeutin** [comment]
Am April 10, 2020 10:03:06 AM UTC schrieb wsavran <notifications@github.com>:
> Merged #21 into dev.

Tnx & happy easter! :)


-- 
sent from my phone

**Pull request merged**
